# Generated by Django 4.1.5 on 2023-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default='Not Provided', max_length=120),
            preserve_default=False,
        ),
    ]
