# Generated by Django 4.1.5 on 2023-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(default='Not Provided', max_length=120),
            preserve_default=False,
        ),
    ]
