# Generated by Django 4.1.5 on 2023-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
