# Generated by Django 4.1.5 on 2023-01-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_in', '0002_dataimport_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_in.datasource')),
            ],
        ),
    ]
