# Generated by Django 4.1.5 on 2023-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_in', '0004_rename_content_type_transformmap_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformmap',
            name='field_map',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
