# Generated by Django 4.1.5 on 2023-01-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_in', '0005_transformmap_field_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScheduledImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('B', 'Bi-weekly'), ('M', 'Monthly')], max_length=1)),
                ('day_name', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('time', models.TimeField()),
                ('transform_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_in.transformmap')),
            ],
        ),
    ]
