# Generated by Django 4.1.5 on 2023-01-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_in', '0006_datasource_url_scheduledimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledimport',
            old_name='day_name',
            new_name='day',
        ),
    ]
